apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
        env: local
    spec:
      containers:
        - name: api
          image: project-1/api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          command: ["/usr/local/bin/api"]
          env:
            - name: ENVIRONMENT
              value: local
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 12
            periodSeconds: 5
