apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
    - host: api.project-1.local
      http:
        paths:
          - backend:
              serviceName: api
              servicePort: 80
