apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          image: sample/api:latest
          imagePullPolicy: Never
          env:
            - name: ENVIRONMENT
              value: local
